// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cropped_voronoi
List cropped_voronoi(NumericMatrix sites);
RcppExport SEXP _SysbioTreemaps_cropped_voronoi(SEXP sitesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sites(sitesSEXP);
    rcpp_result_gen = Rcpp::wrap(cropped_voronoi(sites));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SysbioTreemaps_cropped_voronoi", (DL_FUNC) &_SysbioTreemaps_cropped_voronoi, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_SysbioTreemaps(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
