# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export cropped_voronoi
cropped_voronoi <- function(sites) {
    .Call(`_SysbioTreemaps_cropped_voronoi`, sites)
}

